# Generated by Django 5.1.5 on 2025-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('type', models.TextField()),
                ('param1', models.TextField()),
                ('param2', models.TextField()),
            ],
        ),
    ]
