# Generated by Django 5.1.3 on 2024-11-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(verbose_name='auto_now_add = True'),
        ),
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.TimeField(verbose_name='auto_now_add = True'),
        ),
    ]
