# Generated by Django 5.0.1 on 2025-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_action_date_alter_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
