# Generated by Django 5.0.1 on 2025-02-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_action_date_alter_action_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('opening_time', models.TimeField(verbose_name='Horário de Abertura')),
                ('closing_time', models.TimeField(verbose_name='Horário de Fechamento')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.RenameField(
            model_name='action',
            old_name='param1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='action',
            name='param2',
        ),
        migrations.AlterField(
            model_name='action',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Início')),
                ('end_time', models.DateTimeField(verbose_name='Hora de Término')),
                ('event_type', models.CharField(choices=[('internal', 'Evento Interno'), ('workshop', 'Workshop'), ('visit', 'Visita Agendada'), ('maintenance', 'Manutenção'), ('other', 'Outro')], default='internal', max_length=20, verbose_name='Tipo de Evento')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_time'],
            },
        ),
    ]
