# Generated by Django 5.0.1 on 2025-03-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_labschedule_rename_param1_action_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='action',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='severity',
            field=models.CharField(choices=[('info', 'Informação'), ('warning', 'Atenção'), ('error', 'Erro'), ('critical', 'Crítico'), ('security', 'Segurança')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='action',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['date'], name='logs_action_date_7e67d2_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['severity'], name='logs_action_severit_b7a26c_idx'),
        ),
    ]
