# Generated by Django 5.0.14 on 2025-08-21 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_semestre_unique_together_semestre_usuario_and_more'),
        ('calendario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventocalendario',
            name='calendario__data_in_0041fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventocalendario',
            name='calendario__tipo_ev_1d0e88_idx',
        ),
        migrations.AddIndex(
            model_name='eventocalendario',
            index=models.Index(fields=['usuario', 'tipo_evento'], name='calendario__usuario_544a35_idx'),
        ),
    ]
