# Generated by Django 5.0.14 on 2025-08-12 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "contador_acessos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Contador de Acessos"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Matéria",
                "verbose_name_plural": "Matérias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="AcessoMateria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Hora"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos",
                        to="academico.materia",
                        verbose_name="Matéria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acesso à Matéria",
                "verbose_name_plural": "Acessos às Matérias",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="MaterialDidatico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="materiais/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("TXT", "Texto"), ("DOCX", "Word")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="academico.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Didático",
                "verbose_name_plural": "Materiais Didáticos",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("ano", models.IntegerField(verbose_name="Ano")),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("1", "1º Semestre"),
                            ("2", "2º Semestre"),
                            ("VERAO", "Verão"),
                            ("INVERNO", "Inverno"),
                        ],
                        max_length=10,
                        verbose_name="Período",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Término")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Semestre",
                "verbose_name_plural": "Semestres",
                "ordering": ["-ano", "-periodo"],
                "unique_together": {("ano", "periodo")},
            },
        ),
        migrations.AddField(
            model_name="materia",
            name="semestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materias",
                to="academico.semestre",
                verbose_name="Semestre",
            ),
        ),
        migrations.CreateModel(
            name="EventoAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "escopo",
                    models.CharField(
                        choices=[
                            ("GERAL", "Geral"),
                            ("SEMESTRE", "Semestre"),
                            ("MATERIA", "Matéria"),
                        ],
                        max_length=10,
                        verbose_name="Escopo",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Data e Hora de Início"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e Hora de Término"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AULA", "Aula"),
                            ("PROVA", "Prova"),
                            ("TRABALHO", "Trabalho"),
                            ("ATIVIDADE", "Atividade"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="academico.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="academico.semestre",
                        verbose_name="Semestre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da Agenda",
                "verbose_name_plural": "Eventos da Agenda",
                "ordering": ["data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prazo",
                    models.DateTimeField(blank=True, null=True, verbose_name="Prazo"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="academico.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["prazo", "-criado_em"],
            },
        ),
    ]
