# Generated by Django 5.2.5 on 2025-08-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('hora_fim', models.TimeField(verbose_name='Horário de Término')),
                ('local', models.CharField(blank=True, help_text='Sala, laboratório ou local da aula', max_length=100, verbose_name='Local/Sala')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre a aula', verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='academico.materia', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
                'ordering': ['materia', 'dia_semana', 'hora_inicio'],
                'unique_together': {('materia', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
